apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: cc-tutorial-dev
spec:
  googleServiceAccount: "cc-tutorial-dev@host-343500.iam.gserviceaccount.com"
---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: cc-tutorial-prod
spec:
  googleServiceAccount: "cc-tutorial-prod@host-343500.iam.gserviceaccount.com"
